name: surfel_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.2.2
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.8.18
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.9.0
  - pip:
    - open3d==0.18.0
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - plyfile
    - opencv-python